language: node_js
node_js:
  - '6'
install:
  - npm install && npm install @deskproapps/dpat@0.5.2
script:
  - npm run package
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: M8l0+TWtNBobFXePu0TdU4NgM8Cnh90o6cDUUb2RCwiI9HfY7iWA6RLtQ8vyJOXpY/zlb/tPezXPorQKHu7WeMCAAbGwe9KbxBhnMGpVJJU++pvEipbEw2aJfB/dr0N1DCKFrVeXg25gPQObhqSx6w8zJckDMtVd3bclsPsgGL8Ioh2lUaW9gN3Nl0al87CmPxScbYqxOKeFvFS8e7RDUfjsYqcXlbJZ0gKsu7R9n2MyHMJ5AN1l0j1/qvqOhcG6JUErh4S3bUlV1BwVcNF13CyHaUiwFJ7JuVQKt3UzV5pAAI9V9CZJfm1HkxCDD92rvkv0B54YKea+HuMPQV7SCF+A6s8Xb8tA+W9XYb03aJ2o7cMjrYlZOOKMzsMhV73IbJ0V/hp6rGTi282blAqwXtpkETfixJN3lFuAcSuawmvdklLPRpjD6HXqRmOlWS12GX/Gmfb3XNmjIst+T7EFoh8tyz3BrZ1/9gbzFgA40onKs6dEvWUL9oA5YKDmLZaFpFsGi7vAqnOf/UWRfpxCZ43Bo1fk4vp/ezba3H+ThHG/CVCm5x4vd1XZ2h8jJUbFgXrYwBqFji6UZ5lqOCDGb0L02JUtbvC1Y8wU9Y5ZOl8p7VUvEbRIymFlPdBFXho3iwF7y0aSTmHwzvO2Qpo8CPs2fpseektYKc2iVMaZrvs=
  file: dist/app.zip
  on:
    repo: DeskproApps/labs-auto-self-assign
    tags: true
